/* This file generated by curldefs.lua for use by lua-curl */
{ "AUTH_NONE", 0 },
{ "AUTH_BASIC", (1<<0) },
{ "AUTH_DIGEST", (1<<1) },
{ "AUTH_GSSNEGOTIATE", (1<<2) },
{ "AUTH_NTLM", (1<<3) },
{ "AUTH_DIGEST_IE", (1<<4) },
{ "AUTH_ANY", (~CURLAUTH_DIGEST_IE) },
{ "AUTH_ANYSAFE", (~(CURLAUTH_BASIC|CURLAUTH_DIGEST_IE)) },
