// ---------------------------------------------------------------------------
// luapuz.hpp was generated by puzbind.lua
//
// Any changes made to this file will be lost when the file is regenerated.
// ---------------------------------------------------------------------------

#ifndef luapuz_hpp
#define luapuz_hpp

extern "C" {
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
}

#include "../luapuz_functions.hpp"
#include "../luapuz_tracking.hpp"

// ---------------------------------------------------------------------------
// luapuz
// ---------------------------------------------------------------------------

#include "luapuz_puz_Square.hpp"
#include "luapuz_puz.hpp"
#include "luapuz_puz_Puzzle.hpp"
#include "luapuz_puz_Clue.hpp"
#include "luapuz_std.hpp"
#include "luapuz_puz_Grid.hpp"

LUAPUZ_API int luaopen_luapuz (lua_State *L);
#endif // luapuz_hpp
