// ---------------------------------------------------------------------------
// luapuz_std.hpp was generated by puzbind.lua
//
// Any changes made to this file will be lost when the file is regenerated.
// ---------------------------------------------------------------------------

#ifndef luapuz_std_hpp
#define luapuz_std_hpp

extern "C" {
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
}

#include "../luapuz_functions.hpp"
#include "../luapuz_tracking.hpp"

// ---------------------------------------------------------------------------
// namespace std
// ---------------------------------------------------------------------------

#include <vector>
#include "puz/Square.hpp"

// typedef vector<puz::Square*>
//-------------

LUAPUZ_API void luapuz_checkSquareVector(lua_State * L, int index, std::vector<puz::Square*> * squares);

LUAPUZ_API int luapuz_pushSquareVector(lua_State * L, std::vector<puz::Square*> * squares);

#endif // luapuz_std_hpp
