/* This file generated by curldefs.lua for use by lua-curl */
{ "NETRC_IGNORED", (int) CURL_NETRC_IGNORED },
{ "NETRC_OPTIONAL", (int) CURL_NETRC_OPTIONAL },
{ "NETRC_REQUIRED", (int) CURL_NETRC_REQUIRED },
