// ---------------------------------------------------------------------------
// xword.h - headers and wxLua types for wxLua binding
//
// This file was generated by genwxbind.lua 
// Any changes made to this file will be lost when the file is regenerated
// ---------------------------------------------------------------------------

#ifndef __HOOK_WXLUA_xword_H__
#define __HOOK_WXLUA_xword_H__

#include "wxbind/include/wxcore_bind.h"

#include "wxlua/wxlstate.h"
#include "wxlua/wxlbind.h"

// ---------------------------------------------------------------------------
// Check if the version of binding generator used to create this is older than
//   the current version of the bindings.
//   See 'bindings/genwxbind.lua' and 'modules/wxlua/wxldefs.h'
#if WXLUA_BINDING_VERSION > 35
#   error "The WXLUA_BINDING_VERSION in the bindings is too old, regenerate bindings."
#endif //WXLUA_BINDING_VERSION > 35
// ---------------------------------------------------------------------------

// binding class
class WXLUA_NO_DLLIMPEXP wxLuaBinding_xword : public wxLuaBinding
{
public:
    wxLuaBinding_xword();


private:
    DECLARE_DYNAMIC_CLASS(wxLuaBinding_xword)
};


// initialize wxLuaBinding_xword for all wxLuaStates
extern WXLUA_NO_DLLIMPEXP wxLuaBinding* wxLuaBinding_xword_init();

// ---------------------------------------------------------------------------
// Includes
// ---------------------------------------------------------------------------

#include "../../lua/luapuz/bind/luapuz.hpp"
#include "../../lua/luapuz/bind/luapuz_puz_Puzzle_helpers.hpp"
#include "../../lua/wxbind/include/wxaui_bind.h"
#include "../App.hpp"
#include "../MyFrame.hpp"
#include "../PuzEvent.hpp"
#include "../dialogs/PrintDialog.hpp"
#include "../paths.hpp"

// ---------------------------------------------------------------------------
// Lua Tag Method Values and Tables for each Class
// ---------------------------------------------------------------------------

extern WXLUA_NO_DLLIMPEXP_DATA(int) wxluatype_MyFrame;
extern WXLUA_NO_DLLIMPEXP_DATA(int) wxluatype_PrintInfo;
extern WXLUA_NO_DLLIMPEXP_DATA(int) wxluatype_wxPuzEvent;



#endif // __HOOK_WXLUA_xword_H__

