// ---------------------------------------------------------------------------
// xword.h - headers and wxLua types for wxLua binding
//
// This file was generated by genxwordbind.lua 
// Any changes made to this file will be lost when the file is regenerated
// ---------------------------------------------------------------------------

#ifndef __HOOK_WXLUA_xword_H__
#define __HOOK_WXLUA_xword_H__

#include "wxbind/include/wxcore_bind.h"

#include "wxlua/include/wxlstate.h"
#include "wxlua/include/wxlbind.h"

// ---------------------------------------------------------------------------
// Check if the version of binding generator used to create this is older than
//   the current version of the bindings.
//   See 'bindings/genwxbind.lua' and 'modules/wxlua/include/wxldefs.h'
#if WXLUA_BINDING_VERSION > 27
#   error "The WXLUA_BINDING_VERSION in the bindings is too old, regenerate bindings."
#endif //WXLUA_BINDING_VERSION > 27
// ---------------------------------------------------------------------------

// binding class
class WXLUA_NO_DLLIMPEXP wxLuaBinding_xword : public wxLuaBinding
{
public:
    wxLuaBinding_xword();


private:
    DECLARE_DYNAMIC_CLASS(wxLuaBinding_xword)
};


// initialize wxLuaBinding_xword for all wxLuaStates
extern WXLUA_NO_DLLIMPEXP bool wxLuaBinding_xword_init();

// ---------------------------------------------------------------------------
// Includes
// ---------------------------------------------------------------------------

#include "../App.hpp"
#include "../MyFrame.hpp"
#include "../paths.hpp"
#include "../puz/XGrid.hpp"
#include "../puz/XPuzzle.hpp"
#include "../puz/XSquare.hpp"
#include <vector>

// ---------------------------------------------------------------------------
// Lua Tag Method Values and Tables for each Class
// ---------------------------------------------------------------------------

extern WXLUA_NO_DLLIMPEXP_DATA(int) wxluatype_MyFrame;
extern WXLUA_NO_DLLIMPEXP_DATA(int) wxluatype_XGrid;
extern WXLUA_NO_DLLIMPEXP_DATA(int) wxluatype_XPuzzle;
extern WXLUA_NO_DLLIMPEXP_DATA(int) wxluatype_XSquare;


// ---------------------------------------------------------------------------
// Encapsulation Declarations - need to be public for other bindings.
// ---------------------------------------------------------------------------

wxLUA_DECLARE_ENCAPSULATION(WXLUA_NO_DLLIMPEXP, XGrid, XGrid)
wxLUA_DECLARE_ENCAPSULATION(WXLUA_NO_DLLIMPEXP, XPuzzle, XPuzzle)
wxLUA_DECLARE_ENCAPSULATION(WXLUA_NO_DLLIMPEXP, XSquare, XSquare)


#endif // __HOOK_WXLUA_xword_H__

